<TestLog>
	<TestSuite name="Expression_Solver_Unit_Tests">
		<TestCase name="Add_To_Tree_List">
			<Error file="../test/Expression_Tree/addToTreeList.h" line="27">exception
				std::exception is expected</Error>
			<TestingTime>0</TestingTime>
		</TestCase>
		<TestCase name="Compute_Addition_Subtraction">
			<TestingTime>0</TestingTime>
		</TestCase>
		<TestCase name="Compute_Multiplication_Division">
			<TestingTime>0</TestingTime>
		</TestCase>
		<TestCase name="Compute_Predefined_Function">
			<Error file="../test/Expression_Tree/compute.h" line="34">check
				temp.compute() == 2 failed</Error>
			<TestingTime>0</TestingTime>
		</TestCase>
		<TestCase name="Compute_Variables">
			<TestingTime>0</TestingTime>
		</TestCase>
		<TestCase name="Compute_CustomFunctions">
			<TestingTime>0</TestingTime>
		</TestCase>
		<TestCase name="Compute_Factorial">
			<TestingTime>0</TestingTime>
		</TestCase>
		<TestCase name="Compute_Negative">
			<TestingTime>0</TestingTime>
		</TestCase>
	</TestSuite>
</TestLog>